Add missing java api for StreamTestKit
apache/incubator-pekko pull request #1049
Opened 2024-01-26 09:09 UTC by naosense

To resolve #970

2024-01-26 09:48 UTC, He-Pin commented on stream-testkit/src/main/scala/org/apache/pekko/stream/testkit/StreamTestKit.scala
> +     * val ret = within(50 millis) {
delete or rewrite this code as java:)

2024-01-26 09:49 UTC, He-Pin commented on stream-testkit/src/main/scala/org/apache/pekko/stream/testkit/StreamTestKit.scala
> +    def within[T](min: java.time.Duration, max: java.time.Duration)(f: => T): T =
`(f: => T)` should be `f( function.Function<T>)`

2024-01-26 09:52 UTC, He-Pin commented on stream-testkit/src/main/scala/org/apache/pekko/stream/testkit/StreamTestKit.scala
> +    def within[T](max: java.time.Duration)(f: => T): T = probe.within(max.asScala)(f)
f => T should be `function.Function[Unit, T]`

2024-01-26 09:54 UTC, He-Pin commented
Thanks: here is some of my feedback:
1. no curried method in Java dsl
2. use the functions in `japi.function.Function` instead.
3. If you can write some spec to tests this api, then what would be nice too.

2024-01-26 10:12 UTC, pjfanning requested changes
looks like a good start

we need the function type changes that @kerr suggested

but we should also really have some basic test coverage of the new functions too

and all new public methods need `@since 1.1.0` in their scaladoc

2024-01-26 11:21 UTC, naosense commented
> 3. If you can write some spec to tests this api, then what would be nice too.

@He-Pin there is no java testcase?  
<img width="348" alt="image" src="https://github.com/apache/incubator-pekko/assets/2225426/eb724570-525b-4730-b2d6-60c7826b2535">

2024-01-26 15:03 UTC, He-Pin commented
> > 3. If you can write some spec to tests this api, then what would be nice too.
> 
> @He-Pin there is no java testcase?  
> <img width="348" alt="image" src="https://github.com/apache/incubator-pekko/assets/2225426/eb724570-525b-4730-b2d6-60c7826b2535">
> 

If you not sure how to write the test cases, I can do a following pr for your pr with tests.

2024-01-29 02:45 UTC, naosense commented
> If you not sure how to write the test cases, I can do a following pr for your pr with tests.

yes please, master pin @He-Pin

2024-03-06 17:41 UTC, pjfanning commented
@naosense @kerr any interest in finishing this? - we might still fit this into 1.1.0-M1 if it can be finished soon

2024-03-06 17:46 UTC, He-Pin commented
> @naosense @kerr any interest in finishing this? - we might still fit this into 1.1.0-M1 if it can be finished soon

I think I can took this on weekend.

2024-03-10 11:13 UTC, closed without merging