Rename github action names to Pekko
apache/incubator-pekko pull request #30
Opened 2022-11-07 19:05 UTC by mdedetrich

This is a precursor to get https://github.com/apache/incubator-pekko/issues/23 working because the status checks are reliant on the name of the check hence why this PR is renaming check names that contain Akka to Pekko so that we don't have to update it again in the future.

2022-11-07 19:08 UTC, pjfanning requested changes

2022-11-07 19:08 UTC, pjfanning commented on .github/workflows/nightly-builds.yml
> +      - name: sbt pekko-cluster-metrics/test
this hasn't yet changed in the build.sbt - I have a PR that starts the process of renaming these modules

2022-11-07 19:08 UTC, pjfanning commented on .github/workflows/scala3-compile.yml
> +          - pekko-stream-tests-tck/Test/compile
I have these changes in a PR that is in progress - but only renames the modules that the PR is renaming

2022-11-07 19:08 UTC, mdedetrich commented
@pjfanning Thanks, I just realized that some of the check names are reliant on modules in sbt so will make this PR a draft now.

2023-02-14 14:05 UTC, pjfanning commented
@mdedetrich can this be closed?

2023-02-14 14:06 UTC, mdedetrich commented
@pjfanning Its still doing valid changes but I have to rebase the PR with all of the changes. Thanks for notifying me of this.

2023-02-14 15:51 UTC, mdedetrich commented
@pjfanning PR is now ready to review

2023-02-14 16:24 UTC, gmethvin approved these changes

2023-02-14 16:32 UTC, pjfanning approved these changes
Lgtm

2023-02-14 16:32 UTC, merged